#FROM命令は、Dockerイメージを作成するためのベースイメージを指定します。
FROM php:8.1-rc-apache
#php:8.1-rc-apacheは、PHP8.1のリリース候補（Release Candidate, RC）版を含む公式イメージで、Apacheウェブサーバーが組み込まれています。
#これにより、PHPで構築されたWebアプリケーションをApacheサーバー上で実行する環境を簡単に用意できます。
ENV TZ Asia/Tokyo